### PR TITLE
Remove markhor_estop and replace with capra_estop.

### PR DESCRIPTION
**Pull request by myriamlacroix**
- Remove markhor_estop (replaced with repo capra_estop).
 - Change launch files to find capra_estop.

### CODE REVIEW

**Comment by saxtot** [comment]
Looks good to me.
@lvanasse did you expect more changes here?

**Comment by lvanasse** [comment]
The submodule for capra_estop is missing. Look in the `estop` that Zackary did.

**Comment by myriamlacroix** [comment]
> The submodule for capra_estop is missing. Look in the `estop` branch, that Zackary did.

When testing, capra_estop was one level higher, directly in the workspace, with other capra_... modules. Is it better to put it in markhor directory?

**Comment by lvanasse** [comment]
Humm no you're right, if we want to follow the "package" philosophy, we should keep capra_estop outside. Although this is dangerous, since markhor will not work unless there's the package in the above directory.

So what do you think about at least adding documentation concerning this dependency in the README, and somehow adding an error message when the package is not found when trying to run roslaunch ?  Maybe test with find_pkg ? http://wiki.ros.org/roslaunch/XML 

What do you think ?

**Comment by myriamlacroix** [comment]
image
I tested removing the package and this message appears. I think it's clear enough?
I will add the documentation in README.

**Comment by lvanasse** [comment]
Awesome and sounds good to me! Thanks, Myriam!

**Review by lvanasse — APPROVED** [review]
:+1: Thank Myriam !

**Pull request merged**
