### PR TITLE
Rename thermal cam launch file

### PR DESCRIPTION
**Pull request by myriamlacroix**

### CODE REVIEW

**Comment by lvanasse** [comment]
Does the camera work plug-and-play ? Did you need to configure anything ? Does it show up in the UI ?

**Comment by myriamlacroix** [comment]
Yes, I just tested it today.
No, just launched purethermal_ros (now capra_thermal_cam) and web_ui.
Yes with the right topic (indicated in capra_thermal_cam repo's README).

**Review by lvanasse — APPROVED** [review]
Good job!

**Review by saxtot — APPROVED** [review]
Same thing, good job!

**Pull request merged**
