### PR TITLE
Remove rosbridge launch from base

### PR DESCRIPTION
**Pull request by GLDuval**
Rosbridge is now launched on startup

### CODE REVIEW

**Comment by lvanasse** [comment]
It would probably be worth it to document the launch sequence and how to configure it.

**Comment by GLDuval** [comment]
Are you talking about how and which modes are launched on boot?

**Comment by lvanasse** [comment]
> Are you talking about how and which nodes are launched on boot?

Yes, and how to configure it on a new Jetson.

**Comment by GLDuval** [comment]
> > Are you talking about how and which nodes are launched on boot?
> 
> 
> 
> Yes, and how to configure it on a new Jetson. 

Where should we document this?

**Comment by lvanasse** [comment]
Humm the README.md is a pretty safe bet. Although, it adds a bit of overhead when modifying it, because you've got to commit each time. 

Then there's the Team's Wiki page. But most of the docs are not there. That should be a team decision how in the future we plan to document things. 

I'm saying that because it might not be obvious to new members, and I'm scared that this feature might get lost if we are not careful to document it.

**Pull request merged**
