### PR TITLE
Fix flippers node and allow all flippers to be controlled at once

### PR DESCRIPTION
**Pull request by GLDuval**
A few lines were causing issues on the master branch, removing some code fixed the issue. The flipper services were also changed to allow all 4 flippers to be activated at once by calling the services.

### CODE REVIEW

**Review by benmalenfant — COMMENTED** [review]
What bug does this fixes, what testing has been done?

**Comment by benmalenfant** [comment]
Some of the lines removed were commited by me to avoid edge cases runaways, we need to look into those if we revert them

**Comment by benmalenfant** [comment]
Could we setup a meeting tomorow(today) to discuss these changes?

**Comment by GLDuval** [comment]
> Could we setup a meeting tomorow(today) to discuss these changes?

I'm a bit busy this weekend but we can meet next friday if you're there

**Comment by GLDuval** [comment]
> What bug does this fixes, what testing has been done?

The curent changes on master cause the flipper node to die on launch, after trying to isolate and fix the issue a lot of weird behaviors occured. But when I was using the code we used during the robocup all the issues were gone. So the changes are what we had during Robocup.

**Comment by saxtot** [comment]
If master is unstable, I would rather go back to this than anything else. I really don't like having a /dev branch sourced by default on the robot.

**Review by benmalenfant — APPROVED** [review]
Let's merge this, we will re-implement some of the removed code later if needed

**Review by saxtot — APPROVED** [review]

**Pull request merged**
